### DISCUSSION TITLE
List all posts of a category

### DISCUSSION THREAD

**Discussion by Raynaudy** [ppoffice/hexo-theme-icarus#1130] [Q&A]
Hi everyone,
I want to use Icarus as my blog theme and I would like to replicate a functionnality seen in this blog : https://leimao.github.io/project/.

Indeed, I would like to be able to create differents posts and then group them by categories and display all posts of a same categories in a page listed in the navbar, as you can see on the example.

I tried several things but couldn't succeed.

Kind regards :)

**Comment by ppoffice** [comment]
@Raynaudy Just add the menu links manually:

```yaml
navbar:
    # Naviagtion menu items
    menu:
        Home: /
        Category1: /link/to/category1
        Category2: /link/to/category2
        Category3: /link/to/category3
```
