### DISCUSSION TITLE
archives，categories和tags这三个的页面是怎么生成的？

### DISCUSSION THREAD

**Discussion by JIeJaitt** [ppoffice/hexo-theme-icarus#1156] [Q&A] [answered]
很好奇顶部关于archives，categories和tags这三个的页面是怎么生成的，因为我们在添加新界面的时候，会生成一个目录和一个.md文件嘛，我们的路由就是对应到那个md文件的，但是archives，categories和tags这三个我在源码里面找不到对应的文件，他们三的页面是怎么生成的呢？
```yml
navbar:
    # Naviagtion menu items
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
```
例如我们新建 /about 路由，则会在source目录下新建一篇 md 文件，然后添加相对应的语法。这样顶部菜单栏的 /about 将会直接导航到这个 md 文件并且显示，但是archives，categories和tags这三个的页面在源码中找不到对应的 md 文件的，他们究竟是如何生成的呢？
