### DISCUSSION TITLE
建议默认开启sidebar中所有侧边栏的sticky为true

### DISCUSSION THREAD

**Discussion by SongBaoru** [ppoffice/hexo-theme-icarus#1213] [General]
安装好icarus用了一会后发现我的挂件和别人的博客都不一样，滑动页面后会跑上面去，找了好一会才知道原来是修改这个配置参数。
固定挂件位置很好用，大多数用户也都开启了，建议就把配置文件改成默认开启吧。

**Comment by JIeJaitt** [comment]
我也是，原来是因为这个。我全部改为`true`了。改了之后美观很多
```yml
sidebar:
    left:
        sticky: true
    right:
        sticky: true
```
