### DISCUSSION TITLE
参考作者的自动部署脚本想把博客换成Github Action 部署总是报错有不支持的语法

### DISCUSSION THREAD

**Discussion by JIeJaitt** [ppoffice/hexo-theme-icarus#1217] [Q&A] [answered]
起初是因为我看到github action部署太方便了，就想着换成github action部署，我原本是通过`hexo d` 插件部署的

我参考是的是作者的配置文件
```bash
name: Deploy Hexo Icarus to GitHub Pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: NODE_ENV=production npx hexo g
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

结果一致报错说我这篇文章中有不支持的语法，就是这个`tab`语法，问题是icarus里面是支持这种写法的，并且我使用`hexo g`在本地是可以正常生成文章的

<img width="923" alt="image" src="https://github.com/ppoffice/hexo-theme-icarus/assets/77219045/83e817e2-55f5-4bd1-a7dd-4703655a1687">

**Comment by JIeJaitt** [comment, marked as answer]
解决了，需要把主题的仓库设为子模块。这里分享下我的脚本：

```yml
name: Build and Deploy Hexo

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Use Node.js 16
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'

    - name: update Theme 🎨 
      run: git submodule update --remote themes/icarus
        
    - name: Install and Build 🔧 
      run: |
        npm install -g hexo-cli
        npm install
        hexo clean
        hexo generate

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./public
        BASE_BRANCH: main
```
