### DISCUSSION TITLE
首页 archive 挂件如何按照年份分组？

### DISCUSSION THREAD

**Discussion by zh0ngtian** [ppoffice/hexo-theme-icarus#1260] [Q&A] [answered]
首页 archive 挂件如何像官方文档这样 https://ppoffice.github.io/hexo-theme-icarus/ 按照年份分组，默认情况下是按照月份分组的

**Comment by ppoffice** [comment, marked as answer]
archive widget的`group_by`不要设置成`monthly`

**Reply by zh0ngtian** [reply]
感谢回答！问一下这个选项在哪里，没有在文档中看到

**Reply by ppoffice** [reply]
这里：https://ppoffice.github.io/hexo-theme-icarus/Widgets/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E6%8C%82%E4%BB%B6/#%E6%96%87%E7%AB%A0%E5%BD%92%E6%A1%A3
但是这个group_by选项默认是不开启的。

**Reply by zh0ngtian** [reply]
我这样设置的，但是不生效，还是按照。我用的主题版本是 5.2.1。
```yaml
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: archives
        group_by: yearly
```
