### DISCUSSION TITLE
想问一下为什么我的highlight没有生效

### DISCUSSION THREAD

**Discussion by hoytzhang** [ppoffice/hexo-theme-icarus#1331] [Q&A] [answered]
我是这样安装使用的

```
$ npm install hexo-theme-icarus
$ hexo config theme icarus
```

> _config.icarus.yml

```
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-dark
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
```

> _config.yml

```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```

最后的展示效果：

![{C5B7E5CE-1EA9-44AA-BCC3-4FE7A44C6B92}](https://github.com/user-attachments/assets/c9c39ede-5540-4f9b-8563-7ba6e74c5d9a)

---

还有一些修改_config.yml的情况提供参考：

```
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
```

会显示hljs的效果

```
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: false
```

代码块会只有背景颜色，代码的文字有大有小乱七八糟的。

**Comment by ppoffice** [comment]
你的代码块注释了php么？https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Reply by hoytzhang** [reply]
> 你的代码块注释了php么？https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

你好，我的代码块都注释了类型的。

![{EF9C420C-F6F1-48E5-A68A-5BCDB8226522}](https://github.com/user-attachments/assets/317aeb2d-1c8a-4dbf-a1e4-28a626ededac)

感觉这个问题很奇怪。我是通过脚本搭建在vercel的。不过目前本地运行也是这个效果。另外下面是我根目录的`package.json`文件

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-feed": "^1.0.3",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-searchdb": "^1.4.1",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-inferno": "^1.0.2",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-renderer-swig": "^1.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-icarus": "^6.1.0"
  },
  "scripts": {
    "dev": "hexo server -p $PORT",
    "build": "hexo generate"
  }
}
```

**Reply by ppoffice** [reply]
检查一下你用的CDN是否能正常连接？换一个试试？

**Reply by hoytzhang** [reply, marked as answer]
> 检查一下你用的CDN是否能正常连接？换一个试试？

解决了：

1. 升级hexo 到最新版本（7.3.0）
2. `_config.yml` 如下配置

```yml
highlight:
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
```
