### DISCUSSION TITLE
如何解决mermaid文字显示不全的问题？

### DISCUSSION THREAD

**Discussion by GanZhiXiong** [ppoffice/hexo-theme-icarus#873] [Q&A] [answered]
我安装hexo-filter-mermaid-diagrams后，实现了mermaid功能，但是文字显示不全。

![image](https://user-images.githubusercontent.com/27394631/125191059-18325400-e273-11eb-9866-1ec84d7a237b.png)

**Comment by GanZhiXiong** [comment, marked as answer]
已解决，修改字体样式即可

``` css
 .label {
    font-weight: normal;
    font-size: .91rem;
  }
```
