### DISCUSSION TITLE
cdn 防盗链导致图片无法正常显示的解决方案

### DISCUSSION THREAD

**Discussion by toulzx** [ppoffice/hexo-theme-icarus#933] [Q&A] [answered]
思路来源：https://github.com/x-cold/yuque-hexo/issues/41

需要添加：
```
<meta name="referrer" content="no-referrer" />
```

针对本主题，虽然在 `_config.icarus.yml` 中的 `head` 可增加 `meta` 标签，但似乎并无作用。

我通过在 `layout/common/article.jsx` 中 `{/* Content/Excerpt */}` 后添加这段代码解决这个问题。

![image](https://user-images.githubusercontent.com/57480529/134160459-35cb817a-c205-4a1d-b8f8-d1c5104cce68.png)

**Comment by ppoffice** [comment, marked as answer]
下面的配置可以添加`<meta name="referrer" content="no-referrer">`：

```yaml
head:
    meta:
        - name=referrer;content=no-referrer
```
