### ISSUE TITLE
Does not transfer fontawesome fonts to public

### ISSUE THREAD

**Issue by RyenNelsen** [ppoffice/hexo-theme-icarus#100]
On `hexo generate` everything goes to plan, but when visiting the website, all the font-awesome fonts are missing. Performing a `ls` in `public/font-awesome/fonts/` returns literally nothing.

**Comment by ppoffice** [comment]
Did you check out the latest version of Icarus?

Now Font Awesome fonts are under `public\vendor\font-awesome\fonts` folder.

**Comment by RyenNelsen** [comment]
I am on the most recent version. The issue is when you generate the public files, they are not copied over to the public folder. So you get 404 errors for those files. Unless you move them over manually.

**Comment by ppoffice** [comment]
So is there anything under `public\vendor\font-awesome\fonts`?

**Comment by RyenNelsen** [comment]
No. There is literally nothing.

**Comment by ppoffice** [comment]
Could you please post your site's _config.yml here?

**Comment by RyenNelsen** [comment]
Base website `_config.yml` or my icarus's `_config.yml`?

**Comment by ppoffice** [comment]
Base one

**Comment by RyenNelsen** [comment]
Sure thing:
```yml
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ryen's Blog
subtitle: Where bad things happen
description: A blog about cybersecurity and programming
author: Ryen Nelsen
author_title: Cybersecurity Specialist & Programmer
avatar: https://gravatar.com/avatar/e732c601f43fd04180823fdce02d35da?s=150
location: California
follow: https://github.com/RyenNelsen
language: en
timezone: America/Los_Angeles

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.ryennelsen.com
root: /
permalink: :year/:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus
```
