### ISSUE TITLE
引入自定义 JS / CSS 的功能

### ISSUE THREAD

**Issue by liziwl** [ppoffice/hexo-theme-icarus#1009]
> Make sure you go through the [Hexo docs](https://hexo.io), [Icarus user manual](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus-User-Guide/), and [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues) to see if the feature you are requesting has been already addressed by others.

**Is your feature request related to a problem? Please describe.**

我想修改 logo 的一些CSS设定来实现暗黑模式下的 logo 反色。

**Describe the solution you'd like**

1. 加入暗色logo配置选项
2. 或加入自动引入 js 或者css文件的接口

**Describe alternatives you've considered**

无

**Additional context**

可以参考 fluid 主题中的配置：

https://github.com/fluid-dev/hexo-theme-fluid/blob/1d524d06af1571aca4a27b3f8efed5604cd24eaf/_config.yml#L201-L207

**Comment by ppoffice** [comment]
https://hexo.io/zh-cn/api/injector.html

**Comment by liziwl** [comment]
谢谢提醒，虽然有点绕，但是实现了暗黑模式。

## scripts/inject.js
全局根据系统的设定改成暗黑模式
```js
const css = hexo.extend.helper.get('css').bind(hexo);
const js = hexo.extend.helper.get('js').bind(hexo);

hexo.extend.injector.register('head_end', () => {
  return css('/css/logo.css');
});

hexo.extend.injector.register('head_end', () => {
  return js('https://cdn.jsdelivr.net/npm/darkreader@4/darkreader.min.js');
});

hexo.extend.injector.register('body_end', () => {
  return js('/js/logo.js');
});
```

## source/js/logo.js
```js
DarkReader.auto({
    brightness: 100,
    contrast: 90,
    sepia: 10
});
```

## source/css/logo.css
暗黑模式下logo的重载入
```css
@media (prefers-color-scheme: dark) {
    .navbar-item.navbar-logo img{
        content:url("/meta-img/logo-dark.svg");
    }
    .footer-logo img{
        content:url("/meta-img/logo-dark.svg");
    }
}
```
