### ISSUE TITLE
WARN  Icarus cannot load plugin "gallary"

### ISSUE THREAD

**Issue by luchaoqi** [ppoffice/hexo-theme-icarus#1109]
**Describe the bug**
`hexo g` would produce the following warning:
```
WARN  Icarus cannot load plugin "gallery"
```

**System and Environment**
`package.json`
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.2"
  },
  "dependencies": {
    "bulma-stylus": "0.8.0",
    "hexo": "^5.0.2",
    "hexo-asset-image": "^1.0.0",
    "hexo-asset-link": "^2.2.1",
    "hexo-blog-encrypt": "^3.1.6",
    "hexo-component-inferno": "^0.11.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-mathjax": "^0.9.0",
    "hexo-front-matter-excerpt": "^0.2.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-light-gallery": "^1.0.2",
    "hexo-log": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-util": "^2.7.0",
    "inferno": "^7.3.3",
    "inferno-create-element": "^7.3.3",
    "js-yaml": "^4.1.0"
  }
}

```
config settings
```
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    # busuanzi: true
    cnzz:
        id: 
        web_id: 
    hotjar:
        site_id: 
    katex: true
    mathjax: true
    outdated_browser: false
    progressbar: false
    gallary: true
```
