### ISSUE TITLE
[Bug] Scrollbar of codeblock with dark highlight theme disappears in Chrome

### ISSUE THREAD

**Issue by cmj2002** [ppoffice/hexo-theme-icarus#1145]
> Make sure you go through the [Hexo docs](https://hexo.io), [Icarus user manual](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus-User-Guide/), and [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues) to see if the bug you are reporting has been already addressed by others.

### Describe the bug
The scrollbar of codeblock with dark highlight theme disappears in Chrome. I have tried `d11y-dark`, `github-dark`, `github-dark-dimmed` and their scrollbars all disappeared. It did not happen in the light theme `github`. Same problem did not happen on Firefox (it use default scrollbar).

Although the scrollbar is not visible, it can still be operated.

The image below is using theme `d11y-dark` :

![image](https://user-images.githubusercontent.com/78460873/201087157-c01698b9-8d87-4018-b76d-30f362819bb1.png)

Same page on FireFox:

![image](https://user-images.githubusercontent.com/78460873/201089194-20517ede-e776-442e-b103-9803b3673778.png)

### System and Environment

**Hexo**: 6.2.0

Output of `hexo --version` : 

```
hexo: 6.2.0
hexo-cli: 4.3.0
os: linux 5.10.16.3-microsoft-standard-WSL2 Ubuntu 20.04.5 LTS (Focal Fossa)
node: 16.18.0
v8: 9.4.146.26-node.22
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.10
openssl: 1.1.1q+quic
cldr: 41.0
icu: 71.1
tz: 2022b
unicode: 14.0
ngtcp2: 0.8.1
nghttp3: 0.7.0
```

**Icarus**: commit 436e134 of this repo, the newest version when writing this issue

**Site configuration file** (part of it) :

```
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```

**Theme configuration file** `config.icarus.yml` (part of it) :

```
article:
    highlight:
        theme: a11y-dark
        clipboard: true
        fold: unfolded
```

**Browser**: Chrome 107.0.5304.89

### To Reproduce

Go to https://e1aaaf01.cmj2002-github-io.pages.dev/ffmpeg-images-to-gif/ in Chrome.

### Expected behavior

A scrollbar should appear.

**Comment by cmj2002** [comment]
I use a color extractor to try to get the color the scrollbar. Seems the colors of the slider and the background are so similar that i was not able to distinguish them ( `rgb(32,32,32)` vs `rgb(40,40,40)` )

Anyway, maybe I shouldn't call it a bug. Should I close the issue?

**Comment by cmj2002** [comment]
I managed to change the CSS style and fix it by adding:

```css
figure.highlight .highlight-body::-webkit-scrollbar-thumb {
  background-color: #808080;
}
```
