### ISSUE TITLE
配置中`update_time`设为`auto`后显示的更新时间为构建时间

### ISSUE THREAD

**Issue by stydxm** [ppoffice/hexo-theme-icarus#1233]
**Bug描述**
简洁清晰地描述你遇到的Bug是什么。
根据[文档](https://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/)将`update_time`设为`auto`，但构建后发现无论是否有过更新，首页和文章页均显示更新日期且为构建时间
目前[我的博客](https://stydxm.com)就是这样的情况

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
（这是我机器上的情况，在线的博客是部署在cf pages，由cf构建的，但该问题同样存在）
```
INFO  Validating config
Inferno is in development mode.
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.19045
node: 20.5.1
acorn: 8.10.0
ada: 2.5.1
ares: 1.19.1
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.55.1
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.10+quic
simdutf: 3.2.14
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.18
v8: 11.3.244.8-node.10
zlib: 1.2.13.1-motley
```
- 站点配置文件`_config.yml`
https://github.com/stydxm/blog/blob/master/_config.yml
- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`
https://github.com/stydxm/blog/blob/master/_config.icarus.yml
- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）
无
- 浏览器版本（如Firefox 70.0，Chrome Android 80.0）
Firefox 116/Chrome 116/Edge 116（与浏览器版本无关）

**复现方式**
`update_time`设为`auto`并进行构建

**期望行为**
文章的更新时间与发布时间相同时隐藏更新时间，不同时显示发布时间与更新时间而非构建时间

**截图**
![SI%X0JF01{0U0N0}0C)%9(Y](https://github.com/ppoffice/hexo-theme-icarus/assets/62790279/349ae99c-876e-411b-af4e-767246eda953)
![8D`L%JQVPA~@J%H6RU9M(TK](https://github.com/ppoffice/hexo-theme-icarus/assets/62790279/0bbc8f81-5884-425c-9b53-8f812db785c0)
![J%`2R(BY)AE5FZDXD0HS)RJ](https://github.com/ppoffice/hexo-theme-icarus/assets/62790279/ef2e66a2-ef3f-4685-ad7c-5c2bc61def31)

**Comment by ppoffice** [comment]
这种情况下需要手动设置`created_at`

**Comment by stydxm** [comment]
> 这种情况下需要手动设置`created_at`

能否在文档里详细写下

**Comment by stydxm** [comment]
> 这种情况下需要手动设置`created_at`

实际效果与文档描述不同也可以算非预期行为吧

**Comment by rinscr3003** [comment]
关键是很难自动的保存你的“书写完成时间”。对操作系统来说是知道文件修改时间的，但是这是文件系统的属性，上传到CI后还有没有是一个问题，CI的时区和作者的时区在不在一起也是一个问题。我曾用过一个主题，它用了CI的时区为当前时区。。。。结果是我刚刚更新的文章也给我显示多少小时前更新。。。这种情况最好还是自己手动去填写一下`created_at`比较好，即使有些主题这个时区问题一言难尽。

**Comment by stydxm** [comment]
> 关键是很难自动的保存你的“书写完成时间”。对操作系统来说是知道文件修改时间的，但是这是文件系统的属性，上传到CI后还有没有是一个问题，CI的时区和作者的时区在不在一起也是一个问题。我曾用过一个主题，它用了CI的时区为当前时区。。。。结果是我刚刚更新的文章也给我显示多少小时前更新。。。这种情况最好还是自己手动去填写一下`created_at`比较好，即使有些主题这个时区问题一言难尽。

可是我按照文档写了`time`和`updated`这两个字段

**Comment by stydxm** [comment]
这个问题挺烦的，每篇文章手动指定`date`和`updated`，但构建出来页面的更新时间还是构建的时间，希望可以修复下
@ppoffice

**Comment by PJ-568** [comment]
您可尝试用 Actions 生成文件后再用 cf 部署，同时您可能需要将 fetch 深度设置为 0 再尝试恢复文件时间：
```yaml release.yml
# 以上省略
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.17.0'

    - name: Restore file modification time
      run: |
        git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
        hexo d

# 以下忽略，部署到 cf
```
