### ISSUE TITLE
FontAwesome之外的图标支持（如 Tabler Icons 等）

### ISSUE THREAD

**Issue by zhutmost** [ppoffice/hexo-theme-icarus#1242]
首先感谢开发者们的工作～

请问能否考虑支持FontAwesome之外的图标？（尤其是一些开源或Free的图标库，目前FontAwesome的大量图标都是收费的）
例如：
- Tabler Icons： https://tabler-icons.io/
- Feather Icons： https://feathericons.com/
- ...

### 备选方案

如果您觉得原生支持的维护工作量过大，或者不太必要的话，能否退而求其次，考虑允许支持本地的SVG图标？例如这样：
```yaml
...
social_links:
  Github:
    icon: /assets/icons/github.svg
    url: https://github.com/somebody
```
可以考虑通过 icon的字符串首字符是否是 "/" 区分是否是一个本地的路径。
