### ISSUE TITLE
Supporting sub-menus

### ISSUE THREAD

**Issue by noraj** [ppoffice/hexo-theme-icarus#1250]
**Is your feature request related to a problem? Please describe.**

I can't have sub-menus.

**Describe the solution you'd like**

Can you support sub-menus when adding a list of several links for example:

```yaml
About: 
    trademark: /about/trademark/
    enterprise: /about/enterprise/
```

cf. https://github.com/ppoffice/hexo-theme-hueman/issues/181 and how I PRed for another theme https://github.com/ppoffice/hexo-theme-hueman/pull/288/files

**Describe alternatives you've considered**

None.
