### ISSUE TITLE
Utterances can't display normally by clicking and navigating to a post but work fine when refreshing the page

### ISSUE THREAD

**Issue by guoapeng** [ppoffice/hexo-theme-icarus#1307]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
简洁清晰地描述你遇到的Bug是什么。

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

```bash
hexo v
INFO  Validating config
Inferno is in development mode.
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
hexo: 7.3.0
hexo-cli: 4.3.2
os: linux 6.8.8-300.fc40.x86_64 Fedora Linux 40 (Workstation Edition)
node: 20.12.2
acorn: 8.11.3
ada: 2.7.6
ares: 1.27.0
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 44.1
icu: 74.2
llhttp: 8.1.2
modules: 115
napi: 9
nghttp2: 1.60.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.13+quic
simdutf: 4.0.8
tz: 2024a
undici: 5.28.4
unicode: 15.1
uv: 1.46.0
uvwasi: 0.0.20
v8: 11.3.244.8-node.19
zlib: 1.3.0.1-motley-40e35a7

```

- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`
```yaml
comment:
    type: utterances
    repo: guoapeng/guoapeng.github.io
    issue_term: pathname        # Required if issue_number is not set
    #issue_number: 100           # Required if issue_term is not set. Every post can be mapped to a separate, manually-created GitHub issue.
    #label: some-issue-label     # Optional
    theme: github-light         # Optional
```
- 浏览器版本（版本 124.0.6367.118（正式版本）Fedora Project （64 位））

**复现方式**
列出复现这个Bug的步骤，如：

1. 访问<https://pengtech.net> click on 友链，或者任何post， 例如[this page](https://pengtech.net/friends/?t=1720697989412), 没有评论界面。

而且打开 开发者工具>console中还有如下错误

```bash
Uncaught DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The element has no parent.
    at https://utteranc.es/client.js:1:1821
    at https://utteranc.es/client.js:1:2220
```

3. 刷新或者按F5， 评论正常显示。

**期望行为**

无论用户通过点击，还是刷新页面，评论应该都能正常显示。之前使用next主题没有类似的问题。

**截图**
通过点击访问页面，没有评论框
![image](https://github.com/ppoffice/hexo-theme-icarus/assets/5491418/cd2868e2-f3d9-4b6f-b854-2992456bb102)

控制台有错误提示：
![image](https://github.com/ppoffice/hexo-theme-icarus/assets/5491418/ea830389-d52e-494d-837b-fc2b6738c45d)

页面渲染的代码
![image](https://github.com/ppoffice/hexo-theme-icarus/assets/5491418/4915cbcf-238a-45d9-9806-67c2b3b297a2)

通过刷新页面F5, 评论显示正常。
![image](https://github.com/ppoffice/hexo-theme-icarus/assets/5491418/adc0faf3-c18e-4d6f-af56-73e3cf28e21e)

**额外上下文**
附上与问题有关的其他上下文信息。
