### ISSUE TITLE
在标题中使用 LaTeX 行内公式会导致 toc 挂件渲染该公式时出现滚动条

### ISSUE THREAD

**Issue by jonathanhu237** [ppoffice/hexo-theme-icarus#1329]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
如果在标题（即 "#", "##", ... 的后面）中使用 LaTeX 公式（MathJax）会导致 toc 挂件中的 LaTex 公式下方出现滚动条。

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
  - Hexo 版本：4.3.2
  - 操作系统：linux 5.15.167.4-microsoft-standard-WSL2 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  - Node.js 版本：20.18.0
- 站点配置文件`_config.yml`

```yml
title: Jonathan Hu's Blog
subtitle: ""
description: "A space for sharing insights on tech, development, and personal experiences in the world of coding and beyond."
keywords: null
author: Jonathan Hu
language: en
timezone: ""
url: https://jonathanhu.tech
permalink: ":year/:month/:day/:title/"
permalink_defaults: null
pretty_urls:
    trailing_index: true
    trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render: null
new_post_name: ":title.md"
default_layout: post
titlecase: false
external_link:
    enable: true
    field: site
    exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
    line_number: true
    auto_detect: false
    tab_replace: ""
    wrap: true
    hljs: false
prismjs:
    preprocess: true
    line_number: true
    tab_replace: ""
index_generator:
    path: ""
    per_page: 10
    order_by: "-date"
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
    type: ""
feed:
    enable: true
    type: atom
    path: atom.xml
    limit: 5
    hub:
    content: false
    order_by: -date
```

- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`

```yml
# Version of the configuration file
version: 5.1.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: /img/logo.png
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: /img/favicon.png
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # Name of the web application (default to the site title)
        name: Jonathan Hu's Blog
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name: JH Blog
        # The start URL of the web application
        start_url: http://jonathanhu.tech/
        # The default theme color for the application
        theme_color:
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color:
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            - # The path to the image file
              src: ""
              # A string containing space-separated image dimensions
              sizes: ""
              # A hint as to the media type of the image
              type:
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title:
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url:
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image:
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name:
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author:
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description:
        # Twitter card type (twitter:card)
        twitter_card:
        # Twitter ID (twitter:creator)
        twitter_id:
        # Twitter Site (twitter:site)
        twitter_site:
        # Google+ profile link (deprecated)
        google_plus:
        # Facebook admin ID
        fb_admins:
        # Facebook App ID
        fb_app_id:
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title:
        # Page description (optional)
        # You should leave this blank for most of the time
        description:
        # Page URL (optional)
        # You should leave this blank for most of the time
        url:
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author:
        # Page publisher (optional)
        # You should leave this blank for most of the time
        publisher:
        # Page publisher logo (optional)
        # You should leave this blank for most of the time
        publisher_logo:
        # Page images (optional)
        # You should leave this blank for most of the time
        image:
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ""
    # URL or path to the website's RSS atom.xml
    rss:
# Page top navigation bar configurations
navbar:
    # Navigation menu items
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    # Links to be shown on the right of the navigation bar
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/jonathanhu237
# Page footer configurations
footer:
    # Copyright text
    # copyright: © 2019
    # Links to be shown on the right of the footer section
    links:
        # Creative Commons:
        #     icon: fab fa-creative-commons
        #     url: https://creativecommons.org/
        # Attribution 4.0 International:
        #     icon: fab fa-creative-commons-by
        #     url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show estimated article reading time
    readtime: true
    # Whether to show updated time. For "auto", shows article update time only when page.updated is set and it is different from page.date
    update_time: false
    # # Article licensing block
    # licenses:
    #     Creative Commons:
    #         icon: fab fa-creative-commons
    #         url: https://creativecommons.org/
    #     Attribution:
    #         icon: fab fa-creative-commons-by
    #         url: https://creativecommons.org/licenses/by/4.0/
    #     Noncommercial:
    #         icon: fab fa-creative-commons-nc
    #         url: https://creativecommons.org/licenses/by-nc/4.0/
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
    # Whether to include pages in the search results
    index_pages: true
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
# comment:
#     type: disqus
#     # Disqus shortname
#     shortname: ""
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
# donates:
#     # "Afdian.net" donate button configurations
#     - type: afdian
#       # URL to the "Afdian.net" personal page
#       url: ""
#     # Alipay donate button configurations
#     - type: alipay
#       # Alipay qrcode image URL
#       qrcode: ""
#     # "Buy me a coffee" donate button configurations
#     - type: buymeacoffee
#       # URL to the "Buy me a coffee" page
#       url: ""
#     # Patreon donate button configurations
#     - type: patreon
#       # URL to the Patreon page
#       url: ""
#     # Paypal donate button configurations
#     - type: paypal
#       # Paypal business ID or email address
#       business: ""
#       # Currency code
#       currency_code: USD
#     # Wechat donate button configurations
#     - type: wechat
#       # Wechat qrcode image URL
#       qrcode: ""
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
# share:
#     type: sharethis
#     # URL to the ShareThis share plugin script
#     install_url: ""
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: profile
      # Author name
      author: Jonathan Hu
      # Author title
      author_title: Stay Hungry. Stay Foolish
      # Author's current location
      location: Sun Yat-sen University
      # URL or path to the avatar image
      avatar: /img/avatar.jpg
      # Whether show the rounded avatar image
      avatar_rounded: true
      # Email address for the Gravatar
      gravatar:
      # URL or path for the follow button
      follow_link: https://github.com/jonathanhu237
      # Links to be shown on the bottom of the profile widget
      #   social_links:
      #       Github:
      #           icon: fab fa-github
      #           url: https://github.com/jonathanhu237
      #       Facebook:
      #           icon: fab fa-facebook
      #           url: https://facebook.com
      #       Twitter:
      #           icon: fab fa-twitter
      #           url: https://twitter.com
      #       Dribbble:
      #           icon: fab fa-dribbble
      #           url: https://dribbble.com
      #       RSS:
      #           icon: fas fa-rss
      #           url: /
    # Table of contents widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: toc
      # Whether to show the index of each heading
      index: true
      # Whether to collapse sub-headings when they are out-of-view
      collapsed: true
      # Maximum level of headings to show (1-6)
      depth: 3
    # Categories widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: categories
    # Recommendation links widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: links
      # Names and URLs of the sites
      links:
          Hexo: https://hexo.io
          Icarus: https://github.com/ppoffice/hexo-theme-icarus
    # Recent posts widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: right
      type: recent_posts
    # Archives widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: right
      type: archives
    # Tags widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: right
      type: tags
      # How to order tags. For example 'name' to order by name in ascending order, and '-length' to order by number of posts in each tags in descending order
      order_by: name
      # Amount of tags to show. Will show all if not set.
      amount:
      # Whether to show tags count, i.e. number of posts in the tag.
      show_count: true
    # Google FeedBurner email subscription widget configurations
    # - # Where should the widget be placed, left sidebar or right sidebar
    #   position: left
    #   type: subscribe_email
    #   # Hint text under the email input
    #   description:
    #   # Feedburner ID
    #   feedburner_id: ""
    # Google AdSense unit configurations
    # - # Where should the widget be placed, left sidebar or right sidebar
    #   position: left
    #   type: adsense
    #   # AdSense client ID
    #   client_id: ""
    #   # AdSense AD unit ID
    #   slot_id: ""
    # Follow.it email subscription widget configurations
    # - # Where should the widget be placed, left sidebar or right sidebar
    #   position: left
    #   type: followit
    #   # Hint text under the email input
    #   description:
    #   # Subscription form action URL
    #   action_url: ""
    #   # Feed claiming verification code
    #   verification_code: ""
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id:
    # Bing Webmaster Tools plugin settings
    # https://www.bing.com/toolbox/webmaster/
    bing_webmaster:
        # Bing Webmaster Tools tracking ID in the <meta> tag
        tracking_id:
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
    # CNZZ statistics
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        id:
        # CNZZ website id
        web_id:
    # Alerting users about the use of cookies
    # https://www.osano.com/cookieconsent/
    cookie_consent:
        # The compliance type. Can be "info", "opt-in", or "opt-out"
        type: info
        # Theme of the popup. Can be "block", "edgeless", or "classic"
        theme: edgeless
        # Whether the popup should stay static regardless of the page scrolls
        static: false
        # Where on the screen the consent popup should display
        position: bottom-left
        # URL to your site's cookie policy
        policyLink: https://www.cookiesandyou.com/
    # Enable the lightGallery and Justified Gallery plugins
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id:
    # Hotjar user feedback plugin
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        site_id:
    # Enable the KaTeX math typesetting support
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Enable PJAX
    pjax: false
    # Show a progress bar at top of the page on page loading
    progressbar: true
    # Statcounter statistics
    # https://statcounter.com/
    statcounter:
        # Statcounter project id
        project:
        # Statcounter project security code
        security:
    # Twitter conversion tracking plugin settings
    # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
    twitter_conversion_tracking:
        # Twitter Pixel ID
        pixel_id:
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: fontawesome
```

- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）

_config.post.yml 如下：

```yml
toc: true
widgets:
    # Table of contents widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: toc
      # Whether to show the index of each heading
      index: true
      # Whether to collapse sub-headings when they are out-of-view
      collapsed: false
      # Maximum level of headings to show (1-6)
      depth: 3
    # Categories widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: categories
    # Tags widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: tags
      # How to order tags. For example 'name' to order by name in ascending order, and '-length' to order by number of posts in each tags in descending order
      order_by: name
      # Amount of tags to show. Will show all if not set.
      amount:
      # Whether to show tags count, i.e. number of posts in the tag.
      show_count: true
plugins:
    mathjax: true
    # Enable page startup animations
    animejs: true
sidebar:
    left:
        sticky: true
```

- 浏览器版本（如Firefox 70.0，Chrome Android 80.0）

Google Chrome 130.0.6723.117

**复现方式**
列出复现这个Bug的步骤，如：

1. 执行 `hexo init` 初始化博客。
2. 使用 `npm` 安装 icarus 主题。
3. 执行 `hexo server` 以生成 icarus 的配置文件。
4. 在 `_config.icarus.yml` 中打开 `mathjax`，即设置 `mathjax: true`。
5. 在 `_posts/hello-world.md`（执行 `hexo init` 时自动生成的文件） 中的 front-matter 部分添加 `toc: true`。
6. 在 `_posts/hello-world.md` 中随便添加一个标题，并在其中包含 LaTeX 代码。
7. 重启 hexo 服务器，即可看到 toc 中 LaTeX 的部分会有一个滚动条。

**期望行为**
toc 挂件中的 LaTeX 公式下不应该有滚动条。

**截图**
![截图](https://github.com/user-attachments/assets/f6e7da54-ad8c-40c0-ae05-bc177afbe63e)
