### ISSUE TITLE
duoshuo href adding duplicate domain name

### ISSUE THREAD

**Issue by fwz** [ppoffice/hexo-theme-icarus#168]
Hi I am trying to setup duoshuo comment plugins under this theme.

Everything goes well except that the link to comment is not correctly formed. For example, on the site "fwz.github.io", every href to the comment button add a redundant domain name ahead of the article    permalink.

![image](https://cloud.githubusercontent.com/assets/5425191/16974472/671041b0-4e6f-11e6-97ba-984c8a5a8370.png)

May I know how should I fix it?

Thanks

**Comment by ppoffice** [comment]
@fwz Try this, plz.

```yml
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://fwz.github.io
root: /
```
