### ISSUE TITLE
Disqus comments and share url is wrong in posts

### ISSUE THREAD

**Issue by meghprkh** [ppoffice/hexo-theme-icarus#170]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

The discus comments button on the main page which lists all the posts and the share button url is wrong. It has the root repeated two times. For example, this is the url of one of the share buttons `https://meghprkh.github.io/blog/blog/2016/07/22/The-state-of-gamepad-support-in-Games/`

The following is my main config:
```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://meghprkh.github.io/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
```
