### ISSUE TITLE
about TOC

### ISSUE THREAD

**Issue by nextmvp** [ppoffice/hexo-theme-icarus#175]
Does it support [TOC]?

**Comment by ppoffice** [comment]
Yes. Just add `toc: true` to the front-matter of your post.

Example:

```yml
title: Being Outside in Fresh Air & How Your Body Loves It
categories:
- LifeStyle
banner: /hexo-theme-icarus/gallery/shoes.jpg
toc: true
```
Duplicate #142
