### ISSUE TITLE
Not able to show quora logo from font awesome

### ISSUE THREAD

**Issue by Logan1x** [ppoffice/hexo-theme-icarus#294]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

![screenshot-2017-12-2 ppoffice hexo-theme-icarus](https://user-images.githubusercontent.com/10944610/33516102-f52f2936-d792-11e7-89f4-95d2f7d46e22.png)
Not able to add quora logo( it in the the link you provided) using these syntax.tried this 
``` 
  social_links:
        github: https://github.com/logan1x
        youtube: https://youtube.com
        twitter: https://twitter.com/herkuch
        linkedin: https://quora.com
        quora: https://quora.com
```
but getting this 
![screenshot-2017-12-2 blag](https://user-images.githubusercontent.com/10944610/33516156-c2531922-d793-11e7-9634-cc7f6977e108.png)

working properly for everything else.
