### ISSUE TITLE
单栏布局如何居中？

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#342]
又来唠叨你了...自己琢磨半天都没弄好。
我profile和sidebar全部关掉，页面依然会居左显示....如果让它居中呢？
![tim 20181014162745](https://user-images.githubusercontent.com/8164505/46914343-2376c900-cfce-11e8-8c68-20d2c9ee1e79.png)

**Comment by ppoffice** [comment]
将profile设置成false，并且sidebar留空。这样正文一栏自动最大化居中了。
```yml
    profile:
        enabled: false # Whether to show profile bar
    sidebar:  # sidebar position, options: left, right or leave it empty
```
