### ISSUE TITLE
关于数学公式渲染的问题

### ISSUE THREAD

**Issue by noahcao** [ppoffice/hexo-theme-icarus#394]
我在本地运行工程(使用hexo s)，文章中的公式可以被正常渲染，如图：
![image](https://user-images.githubusercontent.com/17743251/51374265-761bd000-1b3d-11e9-8933-9332bb5354d3.png)
但是我尝试部署到远端(hexo d -g)之后，对应的内容便不会被渲染：
![image](https://user-images.githubusercontent.com/17743251/51374295-93509e80-1b3d-11e9-9e23-71ac6bbfc345.png)

我检查了对应的html内容，在渲染的情况下，mathjax会生成对应的渲染块：
![image](https://user-images.githubusercontent.com/17743251/51374339-b24f3080-1b3d-11e9-8106-5b7149dd365c.png)

但是在远端的版本，对应公式的位置只是一些script占位符：
![Uploading image.png…]()

我使用了kramed渲染器，对应的_config和package.json如下：
```
// package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-asset-image": "0.0.3",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "jquery": "^3.3.1",
    "jsdom": "^13.1.0"
  }
}
```
```
# 在icarus的_config.yml和icarus文件夹的_config.yml中都添加了：
mathjax:
  enable: true
  per_page: false
```

在线的项目可以在这里查看:[demo](http://blog.jinkuncao.com)

希望可以得到大家的帮助。因为本地的localhost:4000是完全没有问题的，所以我怀疑可能和部署环境有关？我使用的部署是：
```
deploy:
  type: git
  repo: git@github.com:noahcao/xxx.git
  branch: master
```
