### ISSUE TITLE
请问是否支持多说？contacts设置后，有些图标显示不出来。

### ISSUE THREAD

**Issue by cikichen** [ppoffice/hexo-theme-icarus#41]
1,请问是否支持多说？
2，
```
# Contacts
contacts:
  github: '#'
  twitter: '#'
  facebook: '#'
 # dribbble: '#'
  inkedin: "#"
  rss: /atom.xml
```

![](http://ww2.sinaimg.cn/large/62b0904dgw1eveviel796j209203kglj.jpg)

只有两个图标能显示出来
