### ISSUE TITLE
How to override sidebar from post.md

### ISSUE THREAD

**Issue by ArthurJahn** [ppoffice/hexo-theme-icarus#427]
I'm trying to override `sidebar` from `_config.yml` and not being successful.

In `_config.yml` i've left `sidebar` section blank, and in post file the following:
```yml
---
 title: Hello World
 toc: true
 sidebar:
     left:
         sticky: true
 widgets:
     -
         type: toc
         position: left
  ---
```
The widgets works fine, but the sticky sidebar does not.

- [X] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [X] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@ArthurJahn I tested your code and the sticky sidebar works fine. Did you made any changes to the theme layout files? What's your theme's `_config.yml` and what version of Icarus are you using?

**Comment by ArthurJahn** [comment]
Here you are

```yml
# Version of the Icarus theme that is currently used
version: 2.3.0

favicon: /images/favicon.svg
logo: /images/logo.png
title: Wiki MSDAF
subtitle:
description:
author: Arthur Jahn
language: pt-BR
timezone:
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    fb_app_id:
    # Facebook Admin ID
    fb_admins:
    # Twitter ID
    twitter_id:
    # Twitter site
    twitter_site:
    # Google+ profile link
    google_plus:
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        Processos: /processes
        Repositórios: /repositories
        Sobre: /about
    # Navigation bar links to be shown on the right
    links:
        Gitlab:
            icon: fab fa-gitlab
            url: 'https://gitlab.com/gaesi/msdaf'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Gitlab:
            icon: fab fa-gitlab
            url: 'https://gitlab.com/gaesi/msdaf'
# Article display settings
article:
    # Code highlight theme
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    highlight: atom-one-light
    # Whether to show article thumbnail images
    thumbnail: true
    # Whether to show estimate article reading time
    readtime: true
# Search plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Search-Plugins
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Comment-Plugins
comment:
    # Name of the comment plugin
    type:
# Share plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Share-Plugins
share:
    # Share plugin name
    type:
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
# Intentionally left blank for each page to override it.
# sidebar:
    # left sidebar settings
    # left:
        # Whether the left sidebar is sticky when page scrolls
        # http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        # sticky: false
    # right sidebar settings
    # right:
        # Whether the right sidebar is sticky when page scrolls
        # http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        # sticky: false
# Sidebar widget settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/

# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    google-analytics:
        # Google Analytics tracking id
        tracking_id:
    # Baidu Analytics plugin settings
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id:
    # Hotjar user feedback plugin
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    hotjar:
        # Hotjar site id
        site_id:
    # Show a loading progress bar at top of the page
    progressbar: true
    # Show the copy button in the highlighted code area
    clipboard: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
# CDN provider settings
# http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome
```
If I remove the `sidebar ` from the post file, the toc widget works the same way, but I added the sidebar config to make it sticky, and that's not working.

Thanks for the help!
