### ISSUE TITLE
Google Adsense support

### ISSUE THREAD

**Issue by karthikchintala1** [ppoffice/hexo-theme-icarus#451]
I love the icaurs theme. Can you support Google adsense for this icaus theme?

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by da0mao** [comment]
Create a `adsense.ejs` under `\themes\icarus\layout\widget` folder with code provided by Google.

Add it on widgets section in your **theme** `_config.yml`

```yaml
widgets:
    -
        # Widget name
        type: adsense
        # Where should the widget be placed, left or right
        position: right
```
Not sure if it works perfectly as...

> We're reviewing your site

😭  for weeks
