### ISSUE TITLE
是否可以支持自定义 link widget 的 menu label

### ISSUE THREAD

**Issue by Boycottangent** [ppoffice/hexo-theme-icarus#518]
当前link widget的标签固定是`LINKS`，但实际上这个widget的作用可以很多（考虑到单篇文章的link widget可以在开头修改）那么希望可以自定义这个widget的label，比如`reference`、`related post`之类的。比如像下面这样将这个label作为link widget的一个参数？
```YAML
-
    type: links
    position: left
    label: some links
    links:
        'Website name': 'http://website/url'
        GitHub: 'https://github.com'
```

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
