### ISSUE TITLE
有没有大神帮我解决以下widget出现的显示问题，全部显示在左侧且显示错误

### ISSUE THREAD

**Issue by wangyx1107** [ppoffice/hexo-theme-icarus#624]
如图
![](https://s2.ax1x.com/2020/02/17/3Pn6gg.png)

这个情况会随着blog里的一些代码出现，一旦删除那部分代码，就会恢复正常，比如图中第二篇blog只要加上\< !--more-- \>就会出现该错误，但每次出现错误的代码有所不同，所以查不出原因。
可能是我代码写法存在不当导致的

还有一次是因为\<font color="xxxx"\> \</font\>出错，除了删除导致出错的代码外，未找到解决办法，希望有人指点。

同时在/tags/code下也出现了该错误s

附blog地址: [ARTHAS](https://arthas.org) （暂时删除了导致出错的代码保证首页正常，但/tags/code界面还存在错误）

**Comment by ppoffice** [comment]
@wangyx1107 请移除所有的<font>标签

**Comment by wangyx1107** [comment]
移除所以tag之后没有解决，一旦在第二篇blog中加入readmore还是会出错:)

**Comment by ppoffice** [comment]
@wangyx1107 请附上你的主题源码和配置文件

**Comment by wangyx1107** [comment]
[全部代码blog.tar.gz at https://file.arthas.org/blog.tar.gz ](https://file.arthas.org/blog.tar.gz)

icarus/_config.yml
```
# Version of the Icarus theme that is currently used
version: 2.6.0
# Path or URL to the website's icon
favicon: /images/favicon.svg
# Additional HTML meta tags in an array.
meta: 
# canonical_url of your site
canonical_url: 
# Path or URL to RSS atom.xml
rss: 
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: /images/logo.svg
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    fb_app_id: 
    # Facebook Admin ID
    fb_admins: 
    # Twitter ID
    twitter_id: 
    # Twitter site
    twitter_site: 
    # Google+ profile link
    google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    # Navigation bar links to be shown on the right
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Article display settings
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show code copying button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show article thumbnail images
    thumbnail: false
    # Whether to show estimate article reading time
    readtime: true
# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
#comment:
    # Name of the comment plugin
 #   type: 
# Donation entries
# https://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
#donate:
#    -
        # Donation entry name
#        type: alipay
        # Qrcode image URL
#        qrcode: ''
#    -
        # Donation entry name
       # type: wechat
        # Qrcode image URL
#        qrcode: '/'
#    -
        # Donation entry name
       # type: paypal
        # Paypal business ID or email address
       # business: '/'
        # Currency code
       # currency_code: USD
#    -
        # Donation entry name
#        type: patreon
        # URL to the Patreon page
#        url: '/'
# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
    # Share plugin name
    type: 
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: left
        # Author name to be shown in the profile widget
        author: fAKe 
        # Title of the author to be shown in the profile widget
        author_title: Pleasant Terran
        # Author's current location to be shown in the profile widget
        location: Korhal Terran Dominion  Koprulu Sector
        # Path or URL to the avatar to be shown in the profile widget
        avatar: /images/avatar.jpg 
        # Email address for the Gravatar to be shown in the profile widget
        gravatar: 
        # Whether to show avatar image rounded or square
        avatar_rounded: true
        # Path or URL for the follow button
        follow_link: 'https://shadowstalker.cn'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/wangyx1107'
            QQ:
                icon: fab fa-qq
                url: 'tencent://message/?uin=2226135525&Site=&Menu=yes'
            Steam:
                icon: fab fa-steam
                url: 'https://steamcommunity.com/id/wangyx1107/'
            Email:
                icon: far fa-envelope
                url: 'mailto:shadowstalker.akioi@gmail.com'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/ShadowS65748457'
    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: links
        # Where should the widget be placed, left or right
        position: left
        # Links to be shown in the links widget
        links:
             Google:    'https://www.google.com'
             TosakaUCW: 'https://tosakaucw.github.io'
             Ganmouren: 'https://ganmouren.github.io'
    -
        # Widget name
        type: archive
        # Where should the widget be placed, left or right
        position: left                  
    -
        # Widget name
        type: tagcloud
        # Where should the widget be placed, left or right
        position: right 
    -
        # Widget name
        type: recent_posts
        # Where should the widget be placed, left or right
        position: right
        
    -
        # Widget name
        type: category
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: tag
        # Where should the widget be placed, left or right
        position: right
# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    google-analytics:
        # Google Analytics tracking id
        tracking_id: 
    # Baidu Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id: 
    # Hotjar user feedback plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    hotjar:
        # Hotjar site id
        site_id: 
    # Show a loading progress bar at top of the page
    progressbar: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome

###Add myself
display_updated: true


```
