### ISSUE TITLE
cdn jsdelivr 不生效

### ISSUE THREAD

**Issue by zhangxu3486432** [ppoffice/hexo-theme-icarus#629]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

在默认设置下，静态资源的链接地址没有发生改变。

预期：`https://cdn.jsdelivr.net/gh/user/repo/pic.png`
实际：`https://repo.github.io/pic.png`

官方博客中的图片也是这个问题：`https://blog.zhangruipeng.me/hexo-theme-icarus/images/logo.svg`

```yaml
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome
```
