### ISSUE TITLE
如何在contacts中增加新的选项？

### ISSUE THREAD

**Issue by koalahl** [ppoffice/hexo-theme-icarus#65]
如何在contacts中增加新的选项，如新浪微博等，并且添加对应的图标。谢谢。

**Comment by koalahl** [comment]
Close it. 在以往的问题中搜到了关于contacts的设置方法。fontawesome.io，然后将对应的icon名称填入cantacts中。
例如
```
contacts:
  github: http://github.com/koalahl/
  twitter: 'https://twitter.com/hanangellove'
  weibo: "http://weibo.com/1619592223/"
  rss: atom.xml
```
