### ISSUE TITLE
能否在Navigation Bar里面定义打开新的标签页

### ISSUE THREAD

**Issue by LuchaoQi** [ppoffice/hexo-theme-icarus#720]
比如说我的导航栏里面设置如下:
```
navbar:
    # Naviagtion menu items
    menu:
        Home: /
        Projects: /projects
        About: /about
        Archives: /archives
        # Categories: /categories
        # Tags: /tags
        Resume: link
```

我想要点击`link`的时候实现打开新的标签页的功能而不是在当前页面打开link:
类似html如下的效果
```
<a href="link" target="_blank">Visit external link!</a>
```
