### ISSUE TITLE
右下角如何图标换成array

### ISSUE THREAD

**Issue by zengzhanhang** [ppoffice/hexo-theme-icarus#727]
原来2.3版本我的右下角图标更换成如下的格式
![image](https://user-images.githubusercontent.com/31053687/82114068-fb90ae00-978c-11ea-9625-97144c553999.png)

更换成3.0后想实现同样地效果，但是一直尝试都无法实现，想问下我写得有什么问题，因为我实在没有写过jsx。

我的 `_config.yml` 换成了和2.3一样的格式：
```
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        CC BY-NC-SA 4.0:
            icon:
              - fab fa-creative-commons
              - fab fa-creative-commons-by
              - fab fa-creative-commons-nc
              - fab fa-creative-commons-sa
            url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
```

我把 `..\node_modules\hexo-component-inferno\lib\schema\misc\poly_links.json` 里面 icon.type 改了

```json
    "patternProperties": {
        ".+": {
             ...
                },
                "icon": {
                    "type": [
                        "string",
                        "array"
                    ],
                    "description": "Icon element class name"
                }
```

最后 `footer.jsx` 改成如下：

```jsx
                    <div class="level-end">
                        {Object.keys(links).length ? <div class="field has-addons">
                            {Object.keys(links).map(name => {
                                const link = links[name];
                                return <p class="control">
                                    <a class={`button is-transparent ${link.icon ? 'is-large' : ''}`} target="_blank" rel="noopener" title={name} href={link.url}>
                                        {/* {link.icon ? <i class={link.icon}></i> : name} */}
                                        {link.icon ? typeof link.icon === 'string' ? <i class={link.icon}></i> : 
                                            link.icon.forEach( (val, idx) => {
                                                <i class={val}></i>
                                                // console.log(val)
                                            }) : name}
                                    </a>
                                </p>;
                            })}
                        </div> : null}
                    </div>
```

![](https://user-images.githubusercontent.com/31053687/82114386-2da30f80-978f-11ea-84ec-71a2cf4f57e5.png)

但是最终效果是无法显示
![image](https://user-images.githubusercontent.com/31053687/82114442-680cac80-978f-11ea-99d3-38633d36a3fb.png)
