### ISSUE TITLE
post页面修改成两栏格式之后profile挂件内容缺失

### ISSUE THREAD

**Issue by declan-haojin** [ppoffice/hexo-theme-icarus#753]
**Bug描述**
`post`页面修改成两栏格式之后`profile`挂件内容缺失

**系统与环境**

- icarus: 2020/06/04 直接clone的最新源代码，应该是`3.1.0`

- hexo: `4.2.1`
- hexo-cli: `2.0.0`
- os: `Windows_NT 10.0.18363 win32 x64`
- node: `10.16.3`
- 主题配置文件`themes/icarus/_config.yml`

```yml
-
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: Declan
        # Author title
        author_title: Keep mindful living.
        # Author's current location
        location: Xi'an, China
        # URL or path to the avatar image
        avatar: '/img/avatar.png'
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'mailto:declan@****'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/declan-haojin'
            Instagram:
                icon: fab fa-instagram
                url: 'https://www.instagram.com/***/'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/***'
            # Facebook:
            #     icon: fab fa-facebook
            #     url: 'https://www.facebook.com/profile.php?id=****&ref=bookmarks'
            QQ:
                icon: fab fa-qq
                url: 'https://user.qzone.qq.com/****/'
            RSS:
                icon: fas fa-rss
                url: /atom.xml

```

- 文章`front-matter`

```markdown
title: VRC Change Up 2020-2021 Dev Log
widgets:
- type: profile
position: left
- type: recent_posts
position: left
tags:
- VEX
toc: true
categories:
- VEX Robotics
thumbmail: https://cdn.jsdelivr.net/gh/declan-haojin/blog-image@master/img/20200417004933.png
date: 2020-05-31 23:20:07
```

- Microsoft Edge Chromium `83.0.478.44`
- 在`post`页面按照用户指南更改`frontmatter`里的`widget`之后，原本的圆形头像自动变成了方形，然后缺少了名字下的描述、位置内容和社交媒体图标
- 主页和其他三栏的`post`界面全都是正常的

**期望效果**
![image-20200605012803107](https://cdn.jsdelivr.net/gh/declan-haojin/blog-image@master/img/20200605012923.png)

**实际效果**
![](https://cdn.jsdelivr.net/gh/declan-haojin/blog-image@master/img/20200605013027.png)

****

***也不知道是bug还是我本身配置的问题，希望得到解答，谢谢！***
