### ISSUE TITLE
设置 toc 不用系统提供的 index 失效了

### ISSUE THREAD

**Issue by speam** [ppoffice/hexo-theme-icarus#798]
_config.icarus.yml 文件中配置了：
`-
        position: left
        type: toc
        index: false
`

但是一运行 toc 还是会显示 index。我就是想用我手写的索引，不想用系统自动生成的，现在不知道怎么解决了。
之前这样设置是生效的来着，后来不知道什么原因就失效了。

**Comment by speam** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/42881719/96331211-1a71d400-108e-11eb-900f-0a4f4c0cd5a7.png">
现在就是这个状态，很难受

**Comment by speam** [comment]
知道原因了，是我在 post.md 中设置了：
```
title: Hello World
toc: true
categories: 开始
tag: 111
widgets:
  - type: toc
    position: left
```

这样就会导致 _config.icarus.yml 文件中进行如下设置会失效：
```
-
        position: left
        type: toc
        index: false
```
