### ISSUE TITLE
Not able to generate and deploy to github pages

### ISSUE THREAD

**Issue by Logan1x** [ppoffice/hexo-theme-icarus#813]
**Describe the bug**
I am running hexo theme Icarus and it's running locally fine(giving warning, described below) but when I am pushing to GitHub repo, nothing is loading, When I changed the theme only HTML was loading.

### **Repo link : https://github.com/Logan1x/blag/**

On the local run icarus giving warning as,
```sh
$ hexo server     
INFO  Validating config
Inferno is in development mode.
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
WARN  Theme configurations failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'type',
    dataPath: '.article.licenses',
    schemaPath: '/misc/poly_links.json/type',
    params: { type: 'object,null' },
    message: 'should be object,null'
  }
]
```

**System and Environment**
The version and configuration of Hexo and Icarus.

- Hexo, OS, and node version (use `hexo version` command to view these information)
```BASH
INFO  === Registering Hexo extensions ===
hexo: 5.2.0
hexo-cli: 4.2.0
os: Linux 5.6.19-2-MANJARO linux x64
node: 14.5.0
v8: 8.3.110.9-node.23
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

- Site configuration file `_config.yml`
```yml
title: Blag
subtitle: ''
description: ''
keywords: null
author: Khushal Sharma
language: en
timezone: ''
url: 'http://logan1x.github.io/blag'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: git
  repo: https://github.com/Logan1x/blag.git
  branch: master
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
```

- Theme configuration file `_config.icarus.yml` or `themes/icarus/_config.yml`
```yml
# Version of the configuration file
version: 4.0.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: /img/logo.png
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: /img/favicon.ico
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # Name of the web application (default to the site title)
        name: 
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name: 
        # The start URL of the web application
        start_url: 
        # The default theme color for the application
        theme_color: 
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color: 
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            -
                # The path to the image file
                src: ''
                # A string containing space-separated image dimensions
                sizes: ''
                # A hint as to the media type of the image
                type: 
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: 
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: 
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: 
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: 
        # Twitter card type (twitter:card)
        twitter_card: 
        # Twitter ID (twitter:creator)
        twitter_id: 
        # Twitter Site (twitter:site)
        twitter_site: 
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id: 
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: 
        # Page description (optional)
        # You should leave this blank for most of the time
        description: 
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page images (optional)
        # You should leave this blank for most of the time
        image: 
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss: 
# Page top navigation bar configurations
navbar:
    # Navigation menu items
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: https://logan1x.github.io
    # Links to be shown on the right of the navigation bar
    links:
        Visit on Kaggle:
            icon: fab fa-github
            url: 'https://github.com/logan1x'
        Visit on GitHub:
            icon: fab fa-kaggle
            url: 'https://kaggle.com/logan1x'
# Page footer configurations
footer:
    # Links to be shown on the right of the footer section
    links:
        Kaggle:
            icon: fab fa-kaggle
            url: 'https://www.kaggle.com/logan1x'
        Twitter:
            icon: fab fa-twitter
            url: 'https://twitter.com/herkuch'
        GitHub:
            icon: fab fa-github
            url: 'https://github.com/logan1x'
        Linkedin:
            icon: fab fa-linkedin
            url: 'https://www.linkedin.com/in/khushal-s-679354b2/'
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show estimated article reading time
    readtime: true
    # Article licensing block
    licenses: false
        # Creative Commons:
        #     icon: fab fa-creative-commons
        #     url: 'https://creativecommons.org/'
        # Attribution:
        #     icon: fab fa-creative-commons-by
        #     url: 'https://creativecommons.org/licenses/by/4.0/'
        # Noncommercial:
        #     icon: fab fa-creative-commons-nc
        #     url: 'https://creativecommons.org/licenses/by-nc/4.0/'
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment: false
    # type: disqus
    # # Disqus shortname
    # shortname: ''
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates: false
    # "Afdian.net" donate button configurations
    # -
    #     type: afdian
    #     # URL to the "Afdian.net" personal page
    #     url: ''
    # # Alipay donate button configurations
    # -
    #     type: alipay
    #     # Alipay qrcode image URL
    #     qrcode: ''
    # # "Buy me a coffee" donate button configurations
    # -
    #     type: buymeacoffee
    #     # URL to the "Buy me a coffee" page
    #     url: ''
    # # Patreon donate button configurations
    # -
    #     type: patreon
    #     # URL to the Patreon page
    #     url: ''
    # # Paypal donate button configurations
    # -
    #     type: paypal
    #     # Paypal business ID or email address
    #     business: ''
    #     # Currency code
    #     currency_code: USD
    # # Wechat donate button configurations
    # -
    #     type: wechat
    #     # Wechat qrcode image URL
    #     qrcode: ''
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share: false
    # type: sharethis
    # # URL to the ShareThis share plugin script
    # install_url: ''
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: Khushal Sharma
        # Author title
        author_title: Open Source by Default
        # Author's current location
        location: India
        # URL or path to the avatar image
        avatar: 
        # Whether show the rounded avatar image
        avatar_rounded: false
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fpublish.twitter.com%2F&ref_src=twsrc%5Etfw&screen_name=herkuch&tw_p=followbutton'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/Logan1x'
            Kaggle:
                icon: fab fa-kaggle
                url: 'https://www.kaggle.com/logan1x'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/herkuch'
            Linkedin:
                icon: fab fa-linkedin
                url: 'https://www.linkedin.com/in/khushal-s-679354b2/'
            Email:
                icon: fas fa-envelope
                url: 'https://spamty.eu/show/v6/467/5e93ab70ce6790ee317cfae1/'
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
        # Whether to show the index of each heading
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 3
    # Recommendation links widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: links
        # Names and URLs of the sites
        links: false
            # Hexo: 'https://hexo.io'
            # Bulma: 'https://bulma.io'
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: categories
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: recent_posts
    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: archives
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags
    # Google FeedBurner email subscription widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: false #subscribe_email
        # Hint text under the email input
        description: 
        # Feedburner ID
        feedburner_id: ''
    # Google AdSense unit configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: false #adsense
        # AdSense client ID
        client_id: ''
        # AdSense AD unit ID
        slot_id: ''
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics: false
        # Baidu Analytics tracking ID
        # tracking_id: false
    # Bing Webmaster Tools plugin settings
    # https://www.bing.com/toolbox/webmaster/
    bing_webmaster: false
        # Bing Webmaster Tools tracking ID in the <meta> tag
        # tracking_id: false
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
    # CNZZ statistics
    # https://www.umeng.com/web
    cnzz: false
        # CNZZ tracker id
        # id: false
        # CNZZ website id
        # web_id: false
    # Alerting users about the use of cookies
    # https://www.osano.com/cookieconsent/
    cookie_consent: false
        # # The compliance type. Can be "info", "opt-in", or "opt-out"
        # type: info
        # # Theme of the popup. Can be "block", "edgeless", or "classic"
        # theme: edgeless
        # # Whether the popup should stay static regardless of the page scrolls
        # static: false
        # # Where on the screen the consent popup should display
        # position: bottom-left
        # # URL to your site's cookie policy
        # policyLink: 'https://www.cookiesandyou.com/'
    # Enable the lightGallery and Justified Gallery plugins
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics: false
        # Google Analytics tracking ID
        # tracking_id: false
    # Hotjar user feedback plugin
    # https://www.hotjar.com/
    hotjar: false
        # Hotjar site id
        # site_id:  false
    # Enable the KaTeX math typesetting support
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: false
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Show a progress bar at top of the page on page loading
    progressbar: true
    # Statcounter statistics
    # https://statcounter.com/
    statcounter: false
        # Statcounter project id
        # project: false
        # Statcounter project security code
        # security: false
    # Twitter conversion tracking plugin settings
    # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
    twitter_conversion_tracking: false
        # Twitter Pixel ID
        # pixel_id: false
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: fontawesome
```
- Any additional theme configuration files (post front-matter, `_config.post.yml`, or `_config.page.yml`)
`package.json` file below,
```JSON
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.2.0"
  },
  "dependencies": {
    "bulma-stylus": "^0.8.0",
    "hexo": "^5.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0"
  }
}
```
- Browser and version (e.g., Firefox 70.0, Chrome Android 80.0)
`Tried in both`

**Expected behavior**
A normal icaruas theme with three sample posts.
