### ISSUE TITLE
代码复制按钮无法正常显示

### ISSUE THREAD

**Issue by ce-amtic** [ppoffice/hexo-theme-icarus#825]
**Bug描述**
初次打开网页时，代码框的复制按钮无法正常显示，按 Ctrl+R 刷新后依然不能显示（如图），但是按 Shift+F5 刷新后又可以显示。

反复确认主题配置并未发现问题。去看了一下您的 demo，发现存在同样的问题，想不到是出于什么原因。

**截图**
<img width="480" alt="无标题" src="https://user-images.githubusercontent.com/43514587/103215838-7f2f9180-494f-11eb-959a-0402f86ca401.png">

**Comment by ppoffice** [comment]
请按照issue模板列出你的主题配置以及浏览器环境

**Comment by ce-amtic** [comment]
主题配置

```
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: folded
    thumbnail: true
    readtime: true
    licenses:
```

浏览器是 Google Chrome 87.0，另外使用 Firefox 浏览器（版本不是很清楚）测试过，也存在同样的问题。

**Comment by ppoffice** [comment]
CDN呢？

**Comment by ce-amtic** [comment]
```
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: https://cdn.bootcss.com/font-awesome/5.13.0/css/all.css
```

图标用了国内的 CDN，会不会是这个原因？

**Comment by ppoffice** [comment]
@ce-amtic  请参照https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-cdn%E6%8F%90%E4%BE%9B%E5%95%86/ 将你的CDN换为loli.net

**Comment by ce-amtic** [comment]
已经替换 CDN 配置，但是问题依然存在。

```
providers:
    cdn: loli
    fontcdn: loli
    iconcdn: loli

```

发现 clipboard.js 已经成功加载，但是

```html
<div class="level-right">
    <a href="javascript:;" class="copy" title="Copy" data-clipboard-target="#code-1609503773896788 .code">
        <i class="fas fa-copy"></i>
    </a>
</div>
```

这段代码有时会变成这个样子

```html
<div class="level-right">
</div>
```

两种情况下均能找到 clipboard.js

<img width="416" alt="屏幕截图 2021-01-01 202010" src="https://user-images.githubusercontent.com/43514587/103438613-80bec980-4c6f-11eb-804b-b16679f4f1a6.png">

我发现您的 demo 也存在同样的问题，是我的网络环境导致的吗？

<img width="1132" alt="无标题" src="https://user-images.githubusercontent.com/43514587/103438632-a8159680-4c6f-11eb-9fce-7408999d569a.png">
