### ISSUE TITLE
Breaking changes when updating theme and hexo to latest

### ISSUE THREAD

**Issue by 0xd3xt3r** [ppoffice/hexo-theme-icarus#849]
> Make sure you go through the [Hexo docs](https://hexo.io), [Icarus user manual](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus-User-Guide/), and [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues) to see if the bug you are reporting has been already addressed by others.

**Describe the bug**

**System and Environment**
The version and configuration of Hexo and Icarus.

- Hexo, OS, and node version (use `hexo version` command to view these information)
- hexo: 5.4.0
hexo-cli: 3.1.0
os: Linux 5.4.0-66-generic linux x64
node: 12.18.2
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0

- Site configuration file `_config.yml`
 - Theme configuration file `_config.icarus.yml` or `themes/icarus/_config.yml`
```yml
version: 4.0.0
logo: /images/logo-header.png
variant: default
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/0xd3xt3r'
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by-sa/4.0/'
        Subscribe:
            icon: fa fa-envelope
            url: 'https://mailchi.mp/d744c1f04904/taintedbits'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/0xd3xt3r'
article:
    highlight:
        theme: railscasts
        clipboard: true
        fold: unfolded
    readtime: true
search:
    type: insight
comment:
    type: disqus
    shortname: taintedbits
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        type: profile
        position: left
        author: D3xt3r
        author_title: 0xd3xt3r
        avatar: /images/logo-header.png
        avatar_rounded: false
        follow_link: 'https://mailchi.mp/d744c1f04904/taintedbits'
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/0xd3xt3r'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/0xd3xt3r'
            Subscribe:
                icon: fa fa-envelope-open
                url: 'https://mailchi.mp/d744c1f04904/taintedbits'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        type: recent_posts
        position: right
    -
        type: categories
        position: left
    -
        type: archives
        position: right
    -
        type: tags
        position: left
plugins:
    animejs: false
    gallery: true
    mathjax: false
    hotjar:
        site_id: 
    progressbar: true
    busuanzi: false
    outdated_browser: true
    back_to_top: true
    google_analytics:
        tracking_id: UA-128181439-1
    baidu_analytics:
        tracking_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
head:
    favicon: /images/logo-header.png
    canonical_url: 
    open_graph:
        fb_app_id: 
        fb_admins: 
        twitter_id: 0xd3xt3r
        twitter_site: 
        google_plus: 
    meta: 
    rss: /atom.xml
```
- Any additional theme configuration files (post front-matter, `_config.post.yml`, or `_config.page.yml`)
- Browser and version (e.g., Firefox 70.0, Chrome Android 80.0)

**Expected behavior**

There are lots of things that are breaking
1. Images in the excerpts are not appearing. The images are referring to the incorrect URL for eg <URL>/page/2/image1.png which actually should be <URL>/year/month/date/title/image1.png

**Screenshots**
![image](https://user-images.githubusercontent.com/44285870/110789172-9535c880-8295-11eb-849e-d816631edc75.png)

**Additional context**
Current Deployment: taintedbits (which is not breaking and build using old version)
