### ISSUE TITLE
social_links:的icon不能使用图片链接吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [ppoffice/hexo-theme-icarus#862]
```yml
social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/ganzhixiong'
            CSDN:
                icon: https://img-operation.csdnimg.cn/csdn/silkroad/img/1607569674685.png
                url: 'https://blog.csdn.net/oHaiKuoTianKong1682'
```

icon配置为https://img-operation.csdnimg.cn/csdn/silkroad/img/1607569674685.png 无效。
- 是不支持图片链接吗？
- 只能使用 https://fontawesome.com/ 中的图标吗？
