### ISSUE TITLE
Icarus ad placement within title/nav bar on Chrome

### ISSUE THREAD

**Issue by Kritner** [ppoffice/hexo-theme-icarus#969]
**Describe the bug**
Adsense ad placement can now occur in the "Navbar" on a "full display" view of the icarus theme in Chrome, though not sure when it was introduced. Not sure if there is something that can be changed in the layout to prevent this or not, but it's notoriously difficult to test and confirm when running on localhost, as ads don't display except from the registered domain.

**System and Environment**
The version and configuration of Hexo and Icarus.

- Hexo, OS, and node version (use `hexo version` command to view these information)

```txt
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
hexo: 5.4.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.19042 win32 x64
node: 14.18.0
v8: 8.4.371.23-node.84
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1l
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
```

- Site configuration file `_config.yml`

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kritner's Blog
subtitle: Just tryin to learn some stuff and teach some stuff
description: >-
  Join me in programming/coding, cooking, and controlled rotting of food.  I'm a
  developer who's always trying to learn more; I hope that this blog helps
  reinforce my own knowledge, and help others in theirs!
keywords: programming, how-to, development, tutorial
author: Russ Hammett
language: en
timezone: America/New_York

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.kritner.com
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null

# Writing
new_post_name: ':year:month:day-:title.md'
default_layout: post
titlecase: false
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true
  hljs: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: '-date'
# Category & Tag
default_category: uncategorized
category_map: null
tag_map: null
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: icarus
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: null
# rss
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub: null
  content: true
  content_limit: 140
  content_limit_delim: ...
  order_by: '-date'
  icon: icon.png

# sitemap
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true
  
```

- Theme configuration file `_config.icarus.yml` or `themes/icarus/_config.yml`

```yml
# Version of the configuration file
version: 4.0.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: /images/blog_blackText.png
# Page metadata configurations
head:
  # URL or path to the website's icon
  favicon: /images/favicon.ico
  # Web application manifests configuration
  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  manifest:
    # Name of the web application (default to the site title)
    name: Kritner's Blog
    # The displayed name of the web application
    # when there is not enough space to display full name
    short_name: 
    # The start URL of the web application
    start_url: https://blog.kritner.com
    # The default theme color for the application
    theme_color: "#f7f7f7"
    # A placeholder background color for the application page to display
    # before its stylesheet is loaded
    background_color: "#f7f7f7"
    # The preferred display mode for the website
    display: standalone
    # Image files that can serve as application icons for different contexts
#    icons:
      # -
      #   # The path to the image file
      #   src: ''
      #   # A string containing space-separated image dimensions
      #   sizes: ''
      #   # A hint as to the media type of the image
      #   type: 
  # Open Graph metadata
  # https://hexo.io/docs/helpers.html#open-graph
  open_graph:
    # Page title (og:title) (optional)
    # You should leave this blank for most of the time
    title: 
    # Page type (og:type) (optional)
    # You should leave this blank for most of the time
    type: blog
    # Page URL (og:url) (optional)
    # You should leave this blank for most of the time
    url: 
    # Page cover (og:image) (optional)
    # You should leave this blank for most of the time
    image: 
    # Site name (og:site_name) (optional)
    # You should leave this blank for most of the time
    site_name: 
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author: 
    # Page description (og:description) (optional)
    # You should leave this blank for most of the time
    description: 
    # Twitter card type (twitter:card)
    twitter_card: 
    # Twitter ID (twitter:creator)
    twitter_id: rlhammett
    # Twitter Site (twitter:site)
    twitter_site: twitter.com/rlhammett
    # Google+ profile link (deprecated)
    google_plus: 
    # Facebook admin ID
    fb_admins: 
    # Facebook App ID
    fb_app_id: 
  # Structured data of the page
  # https://developers.google.com/search/docs/guides/intro-structured-data
  structured_data:
    # Page title (optional)
    # You should leave this blank for most of the time
    title: 
    # Page description (optional)
    # You should leave this blank for most of the time
    description: 
    # Page URL (optional)
    # You should leave this blank for most of the time
    url: 
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author: 
    # Page publisher (optional)
    # You should leave this blank for most of the time
    publisher: 
    # Page publisher logo (optional)
    # You should leave this blank for most of the time
    publisher_logo: 
    # Page images (optional)
    # You should leave this blank for most of the time
    image: 
  # Additional HTML meta tags in an array
  meta:
    # Meta tag specified in <attribute>=<value> style
    # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
    - ''
  # URL or path to the website's RSS atom.xml
  rss: atom.xml

# Page top navigation bar configurations
navbar:
  # Navigation menu items
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
  # Links to be shown on the right of the navigation bar
  links:
    Download on GitHub:
      icon: fab fa-github
      url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Page footer configurations
footer:
  # Links to be shown on the right of the footer section
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: 'https://creativecommons.org/'
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: 'https://creativecommons.org/licenses/by/4.0/'
    Download on GitHub:
      icon: fab fa-github
      url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Article related configurations
article:
  # Code highlight settings
  highlight:
    # Code highlight themes
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-light
    # Show copy code button
    clipboard: true
    # Default folding status of the code blocks. Can be "", "folded", "unfolded"
    fold: unfolded
  # Whether to show estimated article reading time
  readtime: true
  # Article licensing block
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: 'https://creativecommons.org/'
    Attribution:
      icon: fab fa-creative-commons-by
      url: 'https://creativecommons.org/licenses/by/4.0/'
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: 'https://creativecommons.org/licenses/by-nc/4.0/'
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
  type: insight
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
  type: disqus
  # Disqus shortname
  shortname: 'kritnerblog'
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
  -
    type: buymeacoffee
    # URL to the "Buy me a coffee" page
    url: 'https://www.buymeacoffee.com/kritner'
  -
    type: paypal
    # Paypal business ID or email address
    business: 'kritner@gmail.com'
    # Currency code
    currency_code: USD
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
#share:
  #type: sharethis
  # URL to the ShareThis share plugin script
  #install_url: ''
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
  # Left sidebar configurations
  left:
    # Whether the sidebar sticks to the top when page scrolls
    sticky: false
  # Right sidebar configurations
  right:
    # Whether the sidebar sticks to the top when page scrolls
    sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
  # Profile widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: profile
    # Author name
    author: Russ Hammett
    # Author title
    author_title: Software Engineer
    # Author's current location
    location: Westminster, MD
    # URL or path to the avatar image
    avatar: 
    # Whether show the rounded avatar image
    avatar_rounded: true
    # Email address for the Gravatar
    gravatar: kritner@gmail.com
    # URL or path for the follow button
    follow_link: 'http://twitter.com/rlhammett'
    # Links to be shown on the bottom of the profile widget
    social_links:
      Github:
        icon: fab fa-github
        url: 'http://github.com/kritner'
      Facebook:
        icon: fab fa-facebook
        url: 'http://facebook.com/kritner'
      Twitter:
        icon: fab fa-twitter
        url: 'http://twitter.com/rlhammett'
      #Dribbble:
      #  icon: fab fa-dribbble
      #  url: 'https://dribbble.com'
      RSS:
        icon: fas fa-rss
        url: /atom.xml
  # Table of contents widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: toc
    # Whether to show the index of each heading
    index: true
    # Whether to collapse sub-headings when they are out-of-view
    collapsed: true
    # Maximum level of headings to show (1-6)
    depth: 3
  # Recommendation links widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: links
    # Names and URLs of the sites
    links:
      Hexo: 'https://hexo.io'
      Bulma: 'https://bulma.io'
  # Categories widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: categories
  # Recent posts widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: recent_posts
  # Archives widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: archives
  # Tags widget configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: tags
  # Google FeedBurner email subscription widget configurations
  #-
    # Where should the widget be placed, left sidebar or right sidebar
    #position: left
    #type: subscribe_email
    # Hint text under the email input
    #description: 
    # Feedburner ID
    #feedburner_id: ''
  # Google AdSense unit configurations
  -
    # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: adsense
    # AdSense client ID
    client_id: 'ca-pub-6309408035070203'
    # AdSense AD unit ID
    slot_id: '4774311427'
  # Follow.it email subscription widget configurations
  #-
    # Where should the widget be placed, left sidebar or right sidebar
    #position: left
    #type: followit
    # Hint text under the email input
    #description: 
    # Subscription form action URL
    #action_url: ''
    # Feed claiming verification code
    #verification_code: ''
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
  # Enable page startup animations
  animejs: true
  # Show the "back to top" button
  back_to_top: true
  # Baidu Analytics plugin settings
  # https://tongji.baidu.com
  baidu_analytics:
    # Baidu Analytics tracking ID
    tracking_id: 
  # Bing Webmaster Tools plugin settings
  # https://www.bing.com/toolbox/webmaster/
  bing_webmaster:
    # Bing Webmaster Tools tracking ID in the <meta> tag
    tracking_id: 
  # BuSuanZi site/page view counter
  # https://busuanzi.ibruce.info
  busuanzi: false
  # CNZZ statistics
  # https://www.umeng.com/web
  cnzz:
    # CNZZ tracker id
    id: 
    # CNZZ website id
    web_id: 
  # Alerting users about the use of cookies
  # https://www.osano.com/cookieconsent/
  cookie_consent:
    # The compliance type. Can be "info", "opt-in", or "opt-out"
    type: info
    # Theme of the popup. Can be "block", "edgeless", or "classic"
    theme: edgeless
    # Whether the popup should stay static regardless of the page scrolls
    static: false
    # Where on the screen the consent popup should display
    position: bottom-left
    # URL to your site's cookie policy
    policyLink: 'https://www.cookiesandyou.com/'
  # Enable the lightGallery and Justified Gallery plugins
  gallery: true
  # Google Analytics plugin settings
  # https://analytics.google.com
  google_analytics:
    # Google Analytics tracking ID
    tracking_id: UA-27429397-5
  # Hotjar user feedback plugin
  # https://www.hotjar.com/
  hotjar:
    # Hotjar site id
    site_id: 
  # Enable the KaTeX math typesetting support
  # https://katex.org/
  katex: false
  # Enable the MathJax math typesetting support
  # https://www.mathjax.org/
  mathjax: false
  # Enable the Outdated Browser plugin
  # http://outdatedbrowser.com/
  outdated_browser: false
  # Show a progress bar at top of the page on page loading
  progressbar: true
  # Statcounter statistics
  # https://statcounter.com/
  statcounter:
    # Statcounter project id
    project: 
    # Statcounter project security code
    security: 
  # Twitter conversion tracking plugin settings
  # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
  twitter_conversion_tracking:
    # Twitter Pixel ID
    pixel_id: 
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  # Name or URL template of the JavaScript and/or stylesheet CDN provider
  cdn: jsdelivr
  # Name or URL template of the webfont CDN provider
  fontcdn: google
  # Name or URL of the fontawesome icon font CDN provider
  iconcdn: fontawesome
```

- Any additional theme configuration files (post front-matter, `_config.post.yml`, or `_config.page.yml`)

Occurs on all posts, include the root of https://blog.kritner.com

- Browser and version (e.g., Firefox 70.0, Chrome Android 80.0)

Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**To Reproduce**
Steps to reproduce the behavior, such as:

* Goto https://blog.kritner.com from Chrome

Does not occur on the other tested browsers of Firefox or Edge

**Expected behavior**
Ads should not show up in the title bar.  I realize that with "auto ads" this may be an impossible ask, but I feel like *usually* the auto ads are pretty decent about "not putting them in the header", so I wonder if something is either borked in Chrome recently, or if navigation menu classes/layout can be changed a bit to make it less likely to get ads placed there.

**Screenshots**

On a "mobile view" width, it's fine:
![image](https://user-images.githubusercontent.com/8814983/142940629-c0217d1c-c5c8-4069-99b7-d32d032c11b2.png)

Normal width:
![image](https://user-images.githubusercontent.com/8814983/142940732-25e629a3-d19d-4c43-99c1-e99537c36fe5.png)

Edge:
![image](https://user-images.githubusercontent.com/8814983/142941808-9e8ff3e3-2e0e-4d35-8914-4be1861f778d.png)

Firefox:
![image](https://user-images.githubusercontent.com/8814983/142941858-3ae39ec8-753b-436d-a619-e9f0229ffeee.png)
